In [ ]:
## Tutorial of pandas,numpy and matplot
# summary of sample code


In [3]:
import tensorflow as tf

In [ ]:
#pandas
#build dataframe
medal = {'country':Series(country),'gold',Series(gold),'silver':Series(silver),'bronze':Series(bronze)}
medaldf = DataFrame(medal)
#condition
bronze_atleast_one_gold = medaldf[['bronze']][medaldf[['gold']]>=1] #medaldf['bronze?'] return boolean
average_bronze = numpy.mean(bronze_atleast_one_gold)
avg_medal_count = medaldf[['gold','silver','bronze']].apply(numpy.mean)
#
medalcounts = medaldf[['gold','silver','bronze']]
points = numpy.dot(medalcount,[4,2,1])
olympicpoints = {'country':Series(country),'points':Series(points)}
plympic_point_df = DataFrame(olympicpoints)
#add new column
dataframe['namefull'] = dataframe['nameFirst'] + " " + dataframe['nameLast']


In [19]:
import numpy as np
a = np.arange(15).reshape(3,5)c
print "array\n",a

array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
print "dimensions of the array\n",a.shape

dimensions of the array
(3, 5)


In [21]:
print "number of axes\n",a.ndim

number od axes
2


In [22]:
print "type of the elements\n",a.dtype.name

type of the elements
int64


In [23]:
print "total number of elements of the array\n",a.size

total number of elements of the array
15


In [24]:
print "empty array\n",np.empty((5,1,2))

empty array
[[[  6.89985600e-310   1.69877476e-316]]

 [[  6.89985480e-310   6.89985480e-310]]

 [[  6.89985480e-310   6.89985480e-310]]

 [[  6.89985480e-310   6.89985480e-310]]

 [[  6.89985480e-310   6.89985480e-310]]]


In [25]:
print "array ones\n",np.ones((5,1),dtype=np.int_)

array ones
[[1]
 [1]
 [1]
 [1]
 [1]]


In [26]:
print "Generate an array full of random numbers,uniformly sampled from [0.0,1.0)\n",np.random.random((5,4))#equals np.random.rand(5,4)

Generate an array full of random numbers,uniformly sampled from [0.0,1.0)
[[ 0.96369275  0.74521233  0.0836822   0.43473691]
 [ 0.84637977  0.27171048  0.1829361   0.41892142]
 [ 0.23198814  0.0062012   0.35417282  0.7703016 ]
 [ 0.54357309  0.13028107  0.73810125  0.01115947]
 [ 0.00943161  0.02138242  0.07721809  0.09815131]]


In [27]:
print "Sample numbers from a Gaussian distribution\n",np.random.normal(50,10,size=(2,3)) #default (mean = 0,s.d. = 1)

Sample numbers from a Gaussian distribution
[[ 54.51750423  47.09931569  42.41535507]
 [ 52.42396013  46.30554842  58.13486003]]


In [34]:
np.random.seed(693) #seed the random number geberator to get same sequence of numbers every time
print "Random integers \n",np.random.randint(0,10,size=(2,3))

Random integers 
[[2 0 5]
 [1 1 3]]


In [37]:
#iterate over rows to compute sum of each column
print "Sum of each column:\n",a.sum(axis=0) #similar operations are min,max,mean
#iterate over columnds to computer sum of each row
print "Sum of each row:\n",a.sum(axis=1)

Sum of each column:
[15 18 21 24 27]
Sum of each row:
[10 35 60]


In [42]:
new = np.random.randint(0,10,size=4)
print new
print "the index of the maximum value in an array:\n",new.argmax() #argmin

[9 1 9 3]
the index of the maximum value in an array:
0


In [62]:
print a
print "Selecting columns 0,2 for every row:\n",a[:,0:3:2]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Selecting columns 0,2 for every row:
[[ 0  2]
 [ 5  7]
 [10 12]]


In [69]:
#accessing using list of indices
b = np.random.rand(5)
print b
indices = np.array([1,1,2,3])
print b[indices]

[ 0.2732834   0.56136226  0.80309824  0.02816901  0.34656847]
[ 0.56136226  0.56136226  0.80309824  0.02816901]


In [74]:
#masking
newa = np.array([(20,25,10,23,26,32,10,5,0),(0,2,50,20,0,1,28,5,0)])
print newa 
#caculating mean
mean = newa.mean()
print mean
#masking
print newa[newa<mean]

[[20 25 10 23 26 32 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
14.2777777778
[10 10  5  0  0  2  0  1  5  0]


In [77]:
print "multiply:\n",a*2
print "\nDivision:\n",a/2.0
print "adding\n",a+b

multiply:
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]

Division:
[[ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]
 [ 5.   5.5  6.   6.5  7. ]]
adding/n [[  0.2732834    1.56136226   2.80309824   3.02816901   4.34656847]
 [  5.2732834    6.56136226   7.80309824   8.02816901   9.34656847]
 [ 10.2732834   11.56136226  12.80309824  13.02816901  14.34656847]]


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

#get the maximum value of a column in pandas
def get_max_column(symbol):
    df = pd.read_csv("data/{}".csv.format(symbol))
    return df['Close'].max()  #df['name'].mean()

#slice date
def set_date():
    #define date range
    start_date='2010-01-22'
    end_date='2010-01-26'
    dates=pd.date_range(start_date,end_date)
    print dates[0]
    
    #create am empty dataframe
    df1=pd.DataFrame(index=dates) #use dates as index otherwise integer
    
    #Read SPY data into temporary dataframe
    dfSPY = pd.read_csv("data/SPY.csv",index_col="Date"),parse_dates=True,usecols=['Date','Adj Close'],na_values=['nan'])
    dfSPY['high','close'].plot() #plot columns
    plt.show()
    
    #join dataframe
    df1=df1.join(dfSPY,how='inner') #can also drop nan value
    df1=df1.dropna() #drop rows having nan value
    
    #Rename column
    dfSPY = df.SPY.rename(columns={'Adj Close':'SPY'})
    #Read in more stocks
    symbols = ['GOOG','IBM','GLD']
    for symbol in symbols:
        df_temp=pd.read,csv("data/{}.csv".format(symbol),index_col='Date',parse_dates=True,usecols=['Date','Adj Close'],na_value=['nan'])
        df_temp=df_temp.rename(columns={'Adj Close':symbol})
        df1=df1.join(df_temp)
        df = df1.dropna(subset=["SPY"])
    #row slicing
    print df.ix['2010-01-01','2010-01-31']
    #column slicing
    print df['GOOG']
    print df[['IBM','GLD']]
    #slice by row and columnc
    print df.ix['2010-03-10':'2010-03-15',['SPY','IBM']]

def plot_data(df,title="Stock prices"):
    ax = df.plot(title=title)
    ax.set_xlabel("Date")
    ax.set_ylabel("Price")
    plt.show()

def plot_selected(df,columns,start_index,end_index):
    plot_data(df.ix[start_index:end_index,columns,title="Selected data"]

def normalize_data(df):
    return df/df.ix[0,:]
              
symbols = ['SPY','GOOG','IBM','GLD']
def get_data(symbols, dates):
    """Read stock data (adjusted close) for given symbols from CSV files."""
    df = pd.DataFrame(index=dates)
    if 'SPY' not in symbols:  # add SPY for reference, if absent
        symbols.insert(0, 'SPY')

    for symbol in symbols:
        df_temp = pd.read_csv(symbol_to_path(symbol), index_col='Date',
                parse_dates=True, usecols=['Date', 'Adj Close'], na_values=['nan'])
        df_temp = df_temp.rename(columns={'Adj Close': symbol})
        df = df.join(df_temp)
        if symbol == 'SPY':  # drop dates SPY did not trade
            df = df.dropna(subset=["SPY"])

    return df    

In [ ]:
stat = df1.mean() #median,std,sum,prod,mode
dates = pd.date_range('2012-01-01','2012-12-31')
symbols = ['SPY']
df = get_data(symbols,dates)
#PLOT SPY DATA retain matplotlib axis object
ax = df['SPY'].plot(title="SPY rolling mean",label='SPY')
#compute rolling mean using a 20-day window
rm_SPY = pd.rolling.mean(df['SPY'],window=20)
#add rolling mean to same plot
rm_SPY.plot(label="Rolling mean",ax=ax)
def get_rolling_mean(values,window):
    return pd.rolling_mean(values,window=window)
def get_rolling_std(values,window):
    return pd.rolling_std(values,window=window)
def get_bollinger_bands(rm,rstd):
    upper_band = rm + rstd*2
    lower_band = rm - rstd*2
    return upper_band,lower_band
def compute_daily_returns(df):
    daily_returns = (df/df.shift(1))-1
    daily_returns.ix[0,:]=0 #leaves the 0th row full of NANs
    return daily_returns
def fill_missing_values(df_data):
    df_data.fillna(method="ffill".inplace="TRUE")
    df_data.fillna(method="bfill".inplace="TRUE")

In [ ]:
#plot histogram
daily_returns.hist(bins=20) #change no. of bins to 20
#get mean and standard deviation
mean = daily_returns['SPY'].mean()
std = daily_returns['SPY'].std()

plt.axvline(mean,color='w',linestyle='dashed',linewidth=2)
plt.axvline(std,color='r',linestyle="dashed",linewidth=2)
plt.axvline(-std,color='r',linestyle="dashed",linewidth=2)
plt.show()

#plot two histogram together
dates = pd.date_range('2009-01-01','2012-12-31')
symbols = ['SPY','XOM']
df = get_data(symbols,dates)
daily_returns = compute_daily_returns(df)
daily_returns['SPY'].hist(bins=20,label="SPY")
daily_returns['XOM'].hist(bins=20,label="XOM")
plt.legend(loc='upper right')
plt.show()

#scatterplot
daily_return.plot(kind='scatter',x='SPY',y='XOM')
beta_XOM,alpha_XOM=np.polyfit(daily_returns['SPY'],daily_returns['XOM'],1) #polynpmial order 1
plt.plot(daily_returns['SPY'],beta_XOM*daily_returns['SPY']+alpha_XOM,'-',color='r')
plt.show()

daily_return.plot(kind='scatter',x='SPY',y='GLD')
plt.show()
